server:
  port: 8084
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service      # dùng service name đăng ký với Eureka
          predicates:
            - Path=/api/users/**
        - id: order-service
          uri: lb://order-service     # tương tự
          predicates:
            - Path=/api/orders/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka